### ISSUE TITLE
[Feature Request] Trading Terminal

### ISSUE THREAD

**Issue by LawOfSynergy** [refinedmods/refinedstorageaddons#57]
A trading terminal for multiplayer servers.

My idea is that trades can be set by a specialized pattern item.

Constraints that come to mind:
- A new permission might need to be added to the security terminal to whitelist people who can participate in trading.

- Trade terminals (and maybe trade patterns themselves) can be configured to be public, or require trade permissions 

- editing of trades themselves must still be subject to the network's security policy

**Comment by raoulvdberge** [comment]
Nice idea but I don't think it fits this mod.
