### ISSUE TITLE
Crash When Using Key for "Open Wireless Crafting Grid" when out of Range

### ISSUE THREAD

**Issue by wojoeraf** [refinedmods/refinedstorageaddons#59]
Crashed when using key for "Open Wireless Crafting Grid" when out of range.
[crash-2020-07-16_18.02.37-server.txt](https://github.com/refinedmods/refinedstorageaddons/files/4932679/crash-2020-07-16_18.02.37-server.txt)

**Comment by raoulvdberge** [comment]
The 1.12.2 version is no longer maintained.
