### ISSUE TITLE
Is this not already a part of Refined Storage?

### ISSUE THREAD

**Issue by lulabyte** [refinedmods/refinedstorageaddons#64]
We only have the Refined Storage mod installed, but I see a wireless crafting grid is already available. Does this mod add something new, or am I otherwise misunderstanding?

Thanks for the great mod!

**Comment by Nydid** [comment]
> 
> 
> We only have the Refined Storage mod installed, but I see a wireless crafting grid is already available. Does this mod add something new, or am I otherwise misunderstanding?
> 
> Thanks for the great mod!

It adds a "Wireless CRAFTING Grid" while Refined Storage adds everything but the crafting grid (eg. grid, Fluid grid, crafting monitor)

**Comment by Timlyminer** [comment]
is there a way to add infinite range and cross dimension ?
