### ISSUE TITLE
Console spam from Wireless Crafting Grid

### ISSUE THREAD

**Issue by jeremiahwinsley** [refinedmods/refinedstorageaddons#68]
I'm not sure how to reproduce this, but this exception has been spamming the console occasionally:

https://gist.github.com/jeremiahwinsley/257c6871e94d2a0badd264cec94e1b2c

Refined Storage version 1.9.13
Refined Storage Addons version 0.7.2

in modpack ATM6 1.7.2

**Comment by jebjordan** [comment]
What's your server I wonder lol

**Comment by raoulvdberge** [comment]
I don't think that should happen anymore on newer builds.
