### ISSUE TITLE
[Bug] 1st hotbar slot not interactable with wireless crafting grid

### ISSUE THREAD

**Issue by Jan-aka-q0** [refinedmods/refinedstorageaddons#71]
When using the wireless crafting grid in a curios slot, and opening it with the keyboard shortcut, the first hotbar slot is not interactable (can't move items to or from the slot)

**RS version:** 1.9.15
**RSA version:** 0.7.3
_(Playing Enigmatica 6 v0.5.9)_

**Comment by radiomike** [comment]
Seeing same thing here. 
Also, the hotbar slot that gets blocked varies depending on which curio slot the grid is in.

RS version: 1.9.15
RSA version: 0.7.3
modpack atm-6 1.7.8
