### ISSUE TITLE
Wireless crafting grid filter slots picking up random items

### ISSUE THREAD

**Issue by xenoflot** [refinedmods/refinedstorageaddons#72]
Hi, playing ATM6 Skyblock (MC 1.16 Pack v1.1.7) on a server.

We've got one player who twice now has wound up with a couple of random items in what I think are filter slots (the four at the top-right of the WCG GUI). Items we've seen are a vanilla stick, and a piece of Inferium Essence and an Infusion Crystal from Mystical Agriculture. Until the items are removed, the GUI inventory slots are empty as if you'd searched an invalid term.

I have no idea how they got there. He has no magnet, no baubles or curious and until today, didn't even have any armour. I've tried placing items there, clicking items in and I think shift-clicking items in, but they've not accepted anything. I have no idea how to test this further, sorry. If you've any suggestions, I'm happy to give them a go.

forge 31.1.66 (according to curseforge page, I'm not in game at the moment)
refinedstorage-1.9.13
refinedstorageaddons-0.7.2

**Comment by raoulvdberge** [comment]
Thanks for the bug report, but I can't do much with it as there are no reproduction steps.
