### ISSUE TITLE
Auto-Machinging Grid Slots

### ISSUE THREAD

**Issue by ilovehans10** [refinedmods/refinedstorageaddons#77]
This is an enhancement idea for adding a slot/block that will allow for sending items to a machine. I recently posted most of this on the main refined storage github but as it isn't in the vein of the main mod so the issue was closed. Most of the text below is edited from the post there.

#### The Idea:
Having a block that worked similar to the crafter where it puts items into a machine. This block can be used to automatically smelt/process items remotely. It would be similar to but unlike the crafter the items would not be put into the processing block (like a furnace) based on a pattern but would instead be put into the processing block after you put them into a processing slot in the inventory screen of a grid. This functionality should be easy to add as the crafter already does roughly the same thing. The item slot that would send the items could be enabled by use of an upgrade that has to be linked to the processing block. 

This would make it so that if I was away from my processing room and wanted some cobble in my inventory smelted but didn't have a pattern I could put the cobble in the processing slot linked to a processing block that would put the cobble in a furnace and then when it was done smelting an importer would pull it back into the system where I could grab it.

**Comment by raoulvdberge** [comment]
No, sorry.
