### ISSUE TITLE
Update.json Down

### ISSUE THREAD

**Issue by CorruptedKino** [refinedmods/refinedstorageaddons#82]
### Describe the bug

The website where the update.json file is located is down

### How can we reproduce this bug or crash?

run a forge server

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.8

### What Refined Storage Addons version is this happening on?

all of them

**Comment by raoulvdberge** [comment]
Yep, intended

**Comment by raoulvdberge** [comment]
The releases on the site are being phased out, so update.json is going away.
