### ISSUE TITLE
game crushed when using wireles crafting grid

### ISSUE THREAD

**Issue by pc03hachibee** [refinedmods/refinedstorageaddons#87]
### Describe the bug

if i use wireless crafting grid game will crash

The game crashed whilst exception in server tick loop Error: java.lang.AbstractMethodError: Method com/refinedmods/refinedstorageaddons/item/WirelessCraftingGridItem.provide(Lcom/refinedmods/refinedstorage/api/network/item/INetworkItemManager;Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/item/ItemStack;Lcom/refinedmods/refinedstorage/inventory/player/PlayerSlot;)Lcom/refinedmods/refinedstorage/api/network/item/INetworkItem; is abstract Exit Code: -1

### How can we reproduce this bug or crash?

just use the wireless crafting grid

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.23

### What Refined Storage Addons version is this happening on?

refinedstorageaddons-0.7.3

### Relevant log output

```shell
The game crashed whilst exception in server tick loop Error: java.lang.AbstractMethodError: Method com/refinedmods/refinedstorageaddons/item/WirelessCraftingGridItem.provide(Lcom/refinedmods/refinedstorage/api/network/item/INetworkItemManager;Lnet/minecraft/entity/player/PlayerEntity;Lnet/minecraft/item/ItemStack;Lcom/refinedmods/refinedstorage/inventory/player/PlayerSlot;)Lcom/refinedmods/refinedstorage/api/network/item/INetworkItem; is abstract Exit Code: -1
```

**Comment by Darkere** [comment]
which RS version are you on?

**Comment by pc03hachibee** [comment]
refinedstorage-1.9.17

**Comment by raoulvdberge** [comment]
there is a new RS addons version available?

**Comment by pc03hachibee** [comment]
10/07/2021  11:25 AM            41,258 AkashicTome-1.4-16.jar
10/19/2021  07:26 PM            20,324 angelring-1.16.5-1.3.4.1.jar
10/07/2021  11:32 AM            46,287 appleskin-forge-mc1.16.x-2.1.0.jar
10/07/2021  12:03 PM            57,279 AutoRegLib-1.6-49.jar
02/01/2022  02:39 PM            87,568 betterbedrockgenerator-1.16.4-0.1.1.jar
10/09/2021  02:45 PM           315,420 Bookshelf-Forge-1.16.5-10.3.29.jar
10/09/2021  03:12 PM           542,045 BotanyPots-1.16.5-7.1.23.jar
02/01/2022  11:41 AM           265,849 botanypotstiers-1.16.5-1.13.jar
02/01/2022  11:41 AM           124,581 BotanyTrees-1.16.5-3.0.5.jar
10/07/2021  11:24 AM           909,445 buildinggadgets-1.16.5-3.8.0.jar
10/20/2021  01:19 AM           211,251 cabletiers-1.16.5-0.52.jar
10/11/2021  02:51 PM           427,749 cagedmobs-1.16.5-1.3.8.jar
10/07/2021  11:24 AM            65,305 charginggadgets-1.3.0.jar
10/19/2021  07:20 PM            93,191 chunkloaders-1.1.7-mc1.16.5.jar
10/07/2021  11:29 AM           622,321 CodeChickenLib-1.16.5-4.0.3.434-universal.jar
10/07/2021  11:17 AM         1,074,217 cofh_core-1.16.5-1.3.1.jar
10/07/2021  11:21 AM           225,523 comforts-forge-1.16.5-4.0.1.3.jar
10/20/2021  07:51 PM           193,910 constructionwand-1.16.5-2.2.jar
10/07/2021  11:15 AM           683,179 CookingForBlockheads_1.16.5-9.3.4.jar
10/07/2021  11:45 AM        11,337,001 create-mc1.16.5_v0.3.2d.jar
10/07/2021  12:02 PM           158,783 Cucumber-1.16.4-4.1.10.jar
10/07/2021  11:21 AM           246,281 curios-forge-1.16.5-4.0.5.3.jar
10/18/2021  07:11 PM           158,268 dankstorage-3.16.jar
01/31/2022  06:39 PM           328,387 easy_villagers-1.16.5-1.0.11.jar
10/09/2021  02:51 PM           183,750 elevatorid-1.16.5-1.7.13.jar
10/07/2021  11:29 AM           214,797 EnderStorage-1.16.5-2.8.0.168-universal.jar
10/07/2021  11:43 AM           100,293 entangled-1.3.6-mc1.16.5.jar
02/01/2022  07:37 PM           344,904 ExtraStorage-1.16.5-1.6.1.jar
10/07/2021  11:18 AM           472,287 FluxNetworks-1.16.5-6.1.7.12.jar
10/07/2021  11:45 AM           422,516 flywheel-1.16-0.2.4.jar
02/01/2022  11:56 AM            59,621 ftb-power-pots-forge-1605.1.2-build.16.jar
10/17/2021  03:31 PM           234,677 gravestone-1.16.5-1.0.6.jar
10/07/2021  11:39 AM            13,470 Industrial+Agriculture[Industrial+Foregoing]-1.16.3-1.7.1(1).jar
10/07/2021  11:36 AM            31,750 Industrial+Agriculture[Mekanism]-1.16.3-1.7.1(1).jar
10/07/2021  11:36 AM            31,750 Industrial+Agriculture[Mekanism]-1.16.3-1.7.1.jar
10/07/2021  11:22 AM         3,582,355 industrial-foregoing-1.16.5-3.2.14.6-14.jar
10/07/2021  11:37 AM         1,103,938 Industrial_AgricultureCore-1.16.5-1.8.13.jar
10/09/2021  02:49 PM           493,742 ironfurnaces-1.16.5-2.7.7.jar
10/07/2021  11:29 AM           122,608 IronJetpacks-1.16.5-4.2.1.jar
10/19/2021  07:20 PM            88,405 itemcollectors-1.1.2-mc1.16.5.jar
02/01/2022  07:35 PM            29,036 JAMD-1.2.4-build.17+mc1.16.5.jar
10/20/2021  07:48 PM           817,187 jei-1.16.5-7.7.1.126.jar
10/07/2021  11:30 AM            24,981 jeiintegration_1.16.5-7.0.1.15.jar
10/07/2021  11:33 AM           232,022 JustEnoughResources-1.16.3-0.12.0.100.jar
10/07/2021  11:19 AM           683,534 Lollipop-1.16.5-3.2.9.jar
10/20/2021  01:10 AM           173,424 MagicalTorches-1.16.5-2.0.0.jar
10/07/2021  11:53 AM           562,853 mcjtylib-1.16-5.0.22.jar
10/07/2021  11:20 AM         8,962,038 Mekanism-1.16.5-10.0.21.448.jar
10/07/2021  11:20 AM           825,150 MekanismAdditions-1.16.5-10.0.21.448.jar
10/07/2021  11:20 AM           945,876 MekanismGenerators-1.16.5-10.0.21.448.jar
10/09/2021  02:48 PM           143,648 metalbarrels-1.16.2-3.3b.jar
10/10/2021  05:47 PM           608,605 mininggadgets-1.7.5.jar
10/20/2021  07:49 PM            58,249 MouseTweaks-2.14-mc1.16.2.jar
10/07/2021  11:27 AM           257,069 MysticalAgradditions-1.16.5-4.2.2.jar
10/07/2021  11:26 AM         1,599,938 MysticalAgriculture-1.16.5-4.2.3.jar
10/06/2021  08:41 AM         6,046,996 OptiFine_1.16.5_HD_U_G8.jar
02/07/2022  04:09 PM           593,114 Patchouli-1.16.4-53.2.jar
10/15/2021  09:05 PM           766,319 pipez-1.16.5-1.2.11.jar
10/18/2021  07:12 PM           228,332 pocketstorage-1.16.5-0.8.1-build.10.jar
10/07/2021  11:19 AM         1,192,090 Powah-1.16.5-2.3.16.jar
02/01/2022  07:46 PM         3,224,062 refinedstorage-1.9.17.jar
10/20/2021  01:19 AM            30,393 refinedstorageaddons-0.7.3.jar
10/09/2021  02:53 PM           112,845 RepairChests-1.16.5-1.7.jar
10/07/2021  11:51 AM           414,291 rftoolsbase-1.16-2.0.11.jar
10/07/2021  11:51 AM           541,026 rftoolsbuilder-1.16-3.1.2.jar
10/07/2021  11:51 AM         1,624,790 rftoolsdim-1.16-7.0.14-beta.jar
10/07/2021  11:52 AM           367,821 rftoolsstorage-1.16-2.0.13.jar
10/07/2021  11:52 AM         1,606,928 rftoolsutility-1.16-3.1.2.jar
10/09/2021  02:54 PM            16,607 RingOfRepair-Forge-1.16.5-1.2.15.jar
02/01/2022  07:54 PM            62,148 rsrequestify-1.16.5-2.1.6.jar
10/19/2021  07:15 PM           127,432 simplemagnets-1.1.2-mc1.16.5.jar
10/09/2021  03:08 PM         3,396,082 simple_sorter-1.16.4-0.0.1.jar
10/07/2021  12:04 PM           498,355 SimplyJetpacks2-1.16.5-2.6.11.2.jar
02/01/2022  07:23 PM         1,479,056 sophisticatedbackpacks-1.16.5-3.15.1.503.jar
10/07/2021  11:33 AM           500,792 StorageDrawers-1.16.3-8.3.0.jar
10/07/2021  12:02 PM           153,654 supermartijn642configlib-1.0.9-mc1.16.jar
10/07/2021  12:02 PM           202,294 supermartijn642corelib-1.0.12-mc1.16.5.jar
10/18/2021  07:13 PM           104,601 tanknull-2.3-1.16.4.jar
10/07/2021  11:48 AM           561,919 thermal_expansion-1.16.5-1.3.0.jar
10/07/2021  11:48 AM         4,430,095 thermal_foundation-1.16.5-1.3.2.jar
10/07/2021  11:48 AM           167,908 thermal_innovation-1.16.5-1.3.0.jar
10/07/2021  11:47 AM           181,544 thermal_locomotion-1.16.5-1.3.0.jar
10/11/2021  03:31 PM            37,088 time-in-a-bottle-1.1.0.jar
10/07/2021  11:22 AM           635,229 titanium-1.16.5-3.2.8.4-10.jar
10/07/2021  11:25 AM            94,627 torchmaster-2.3.8.jar
10/07/2021  11:15 AM        31,748,505 twilightforest-1.16.5-4.0.546-universal.jar
02/03/2022  04:48 PM           143,064 Ultimate+SkyBlock+Resource+Generator-1.16.5-3.0.jar
10/09/2021  01:59 PM            29,421 WailaHarvestability-mc1.16.x-forge-1.1.15.jar
10/09/2021  02:02 PM            31,378 WAWLA-1.16.5-8.0.1.jar
10/07/2021  11:33 AM           375,674 Waystones_1.16.5-7.6.3.jar
10/19/2021  07:23 PM         1,003,625 wormhole-1.1.9-mc1.16.5.jar
10/09/2021  02:07 PM           227,944 wthit-2.10.9-forge.jar
10/20/2021  07:57 PM            17,937 xptome-1.16.5-v2.1.2.jar

**Comment by pc03hachibee** [comment]
dl the latest version refinedstorageaddons-0.7.4 it works fine. i miss read the your question. thank you very much!
