### ISSUE TITLE
Game crashes when (trying to) open the wireless crafting grid (Vault Hunters modpack 1.12.4)

### ISSUE THREAD

**Issue by SamayaNL** [refinedmods/refinedstorageaddons#88]
### Describe the bug

When trying to open the wireless crafting grid from my hotbar, the game simply crashes.
[crash-2022-02-17_01.40.36-server.txt](https://github.com/refinedmods/refinedstorageaddons/files/8104878/crash-2022-02-17_01.40.36-server.txt)

### How can we reproduce this bug or crash?

1. Craft a Wireless Crafting Grid
2. Charge it
3. Link it to network by shift right clicking it to the controller
4. Right click the WCG while in hotbar

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

36.2.23

### What Refined Storage Addons version is this happening on?

0.7.3

**Comment by Darkere** [comment]
Update.

**Comment by SamayaNL** [comment]
That worked.
