### ISSUE TITLE
Crash as I register the wireless crafting grid to the wireless network

### ISSUE THREAD

**Issue by pantsguyapp** [refinedmods/refinedstorageaddons#94]
### Describe the bug

Game crash everytime I right click the wireless grid, after that, everytime I open the crafting grid, it also crashed

### How can we reproduce this bug or crash?

provdied above.

### What Minecraft version is this happening on?

Minecraft 1.16.5

### What Forge version is this happening on?

idk

### What Refined Storage Addons version is this happening on?

refinedstorage-1.9.15

### Relevant log output

```shell
https://pastebin.com/sZD020bn
```

**Comment by Darkere** [comment]
you are 3 versions behind  on RS 1.16
